config/routes.rb
PeakSeason::Application.routes.draw do

  resources :regions do 
  end

  
  resources :items

  get "/local_recipes" => "recipes#local_listing"
  get "/markets/:id/:name" => "markets#detail"  
  get "/in_season" => "items#in_season_listing"
  get "/local_markets" => "markets#local_markets"

  get "/getmarkets" => 'markets#getmarkets'

  root :to  => "site#home"

 

  

  

end

app/models/market.rb
class Market
 include Mongoid::Document
 include Mongoid::Timestamps

	belongs_to :region, :inverse_of => nil
	has_many :market_times

 field :name, 	type: String
 field :image_url, type: String
 field :url, 	type: String
 field :address, 	type: String
 field :description, 	type: String
 # field :latitude, type: Float
 # field :longitude, type: Float
 # attr_accessible :address
  # geocoded_by :address
  # after_validation :geocode
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :set_market, only: [:show, :edit, :update, :destroy]

  # GET /regions/market
  def index
    # render json: market_list
    # render json: @market_array.first['marketname']
  end

  def local_listing
  end

  def getmarkets
    # @market_array = []
   
    # market_id = "1008567"
    # url = "http://search.ams.usda.gov/farmersmarkets/v1/data.svc/zipSearch?zip=90403"
    # # url = "http://search.ams.usda.gov/farmersmarkets/v1/data.svc/mktDetail?id=" + market_id
    
    # market_list = HTTParty.get(url)
  
    #  # newlist = JSON.parse(market_list.body)
    #  JSON.parse(market_list.body)["results"].each do |item|
    #    # @market_array.push(item["id"])

    #    url = "http://search.ams.usda.gov/farmersmarkets/v1/data.svc/mktDetail?id=" + item["id"]
    #    market_detail = HTTParty.get(url)

    #    market = JSON.parse(market_detail.body)["marketdetails"]
    #    market["marketname"] = item["marketname"]
    #    @market_array.push(market)

    #    # puts item["id"]
    #  end
    #  puts @market_array 

    # # render json: market_list
    # render json: @market_array.first['marketname']
 
  end

  # GET /regions/:id/markets/1
  def show

  end

  # GET /regions/:id/markets/new
  def new
    # @region = Region.find(params[:region_id])
    @market = Market.new
    # @market = Market.new
  end

  # GET /regions/:id/marekts1/edit
  def edit
    # @market

      # @market.market_times << MarketTime.new
      
  end

  def geocoder
    myaddress =  Geocoder.search @markets.first['Address']
    render json: myaddress
  end

  def local_markets
     @markets = []

    # @zip is set in ApplicationController
    # url = "http://search.ams.usda.gov/farmersmarkets/v1/data.svc/zipSearch?zip=" + @zip
    # session[:lat] = "37.7833"
    # session[:lng] = "-122.4167"
    # lat = session[:lat]
    # lng = session[:lng]

    # get lat lng from cookies set by javacript in the application controller.
    lat = cookies[:lat].to_s
    lng = cookies[:lng].to_s

    # lat = request.location.latitude.to_s
    # lng = request.location.longitude.to_s
    # puts "lat:" + request.location.latitude.to_s + "lng:" + request.location.longitude.to_s

    # lat = "34.0219"
    # lng = "-118.4814"
    url = "http://search.ams.usda.gov/farmersmarkets/v1/data.svc/locSearch?lat=" + lat + "&lng=" + lng
    puts url
     
    market_list = HTTParty.get(url)
  
     # newlist = JSON.parse(market_list.body)
     JSON.parse(market_list.body)["results"].each do |item|
       # @market_array.push(item["id"])

       # url = "http://search.ams.usda.gov/farmersmarkets/v1/data.svc/mktDetail?id=" + item["id"]
       # market_detail = HTTParty.get(url)

       # market = JSON.parse(market_detail.body)["marketdetails"]
       # market["marketname"] = item["marketname"]
       @markets.push(item)

       # puts item["id"]
     end
     render "markets/local_listing"
  end

  def detail
    # @market 
   
    puts params
    market_id = params[:id]
    @market_name = params[:name]
    
    url = "http://search.ams.usda.gov/farmersmarkets/v1/data.svc/mktDetail?id=" + market_id
    market_detail = HTTParty.get(url)

    @market = JSON.parse(market_detail.body)["marketdetails"]
   
    
    # render json: @market
  end

  # POST /regions/markets
  def create
    @market = Market.new(market_params) 
    if @market.save
      redirect_to @market, notice: 'Region was successfully created.'   
    else
     render action: 'new' 
    end 
  end

  # PATCH/PUT /regions/markets/:id
  def update
    puts params.to_json
    if @market.update(market_params)
      redirect_to region_market_path(@region, @market), notice: 'Market was successfully updated.' 
    else
      render action: 'edit' 
    end
  end

  # DELETE /regions/markets/:id
  def destroy
    @market.destroy
    redirect_to markets_url   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market
      @region = Region.find(params[:region_id])
      # @markets = @region.markets.all

      @market = @region.markets.find(params[:id])
     
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def market_params
      params.require(:market).permit(:name, :image_url, :url, :address, :description)
    end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/_form.html.erb
<%= form_for([@region, @market])  do |f| %>
<!-- WHATS WRONG HERE? -->
  <% if @market.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@market.errors.count, "error") %> prohibited this market from being saved:</h2>
      <ul>
      <% @market.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div>
  <table class="table">
    <tr>
      <th>Day of Week</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Season Start</th>
      <th>Day</th>
      <th>Season End</th>
      <th>Day</th>
    </tr>
  <% @market.market_times.each do |mt| %>
    <%= render "market_times", :time => mt %>
  <% end %>
  </table>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/markets/_market_times.html.erb
<tr>
  <td><%= select_tag "market[market_time][day][]", options_for_select(MarketTime.get_days_array, time.day) %></td>
  <td><%= time_field_tag "market[market_time][start_time][]" %></td>
  <td><%= time_field_tag "market[market_time][end_time][]" %></td>

  <td><%= select_tag "market[market_time][start_month][]", options_for_select(MarketTime.get_months_array) %></td>
  <td><%= number_field_tag "market[market_time][start_day][]" %></td>
  <td><%= select_tag "market[market_time][end_month][]", options_for_select(MarketTime.get_months_array) %></td>
  <td><%= number_field_tag "market[market_time][end_day][]" %></td>
 </tr>
  


<!--   field :day, type: Integer
  field :start_time, type: Time
  field :end_time, type: Time
  
  field :start_month, type: Integer
  field :start_day, type: Integer
  field :end_month, type: Integer
  field :end_day, type: Integer
 -->
    

app/views/markets/detail.html.erb
<% 
my_address = URI.escape(@market['Address'])

%>
<div class="container">
  <div class="row-fluid">
		<div class="span6">
			<a href="<%= @market['GoogleLink'] %>"><img src="http://maps.googleapis.com/maps/api/staticmap?center=<%= my_address %>&zoom=13&size=600x600&maptype=roadmap
		&markers=color:blue%7Clabel:Market%7C<%= my_address %>&markers=color:green%7Clabel:G%7C40.711614,-74.012318
		&markers=color:red%7Ccolor:red%7Clabel:C%7C40.718217,-73.998284&sensor=false" target="map"></a>
		</div>
		<div class="span6">
			<h3><%= URI.unescape(@market_name) %></h3>
			<p><%= @market['Schedule'] %></p>
			<p><a href="<%= @market['GoogleLink'] %>"><%= @market['Address'] %></a></p>
			<p><%= @market['Description'] %></p>
			<p><%= @market['Products'] %></p>
		</div>
	</div>
</div>

app/views/markets/edit.html.erb
<div class="container">
	<h1>Editing Market</h1>

<%= render 'form' %>
Add list of times.  Can destroy or add here.  Add opens a new form.  Destroy redirects to this page.
<%= link_to 'Show', region_market_path(@region, @market) %> |
<%= link_to 'Back', region_markets_path(@region) %>
</div>

app/views/markets/index.html.erb
<div class="container">
<h1>Markets in <%= @region.name %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>URL</th>
      <th>Address</th>
      <th>Description</th>

      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @markets.each do |market| %>
      <tr>
        <td><%= market.name %></td>
        <td><img class="media-object" data-src="holder.js/64x64" width="100" src="<%= market.image_url %>"></td>
        <td><%= market.url %></td>
        <td><%= market.address %></td>
        <td><%= market.description %></td>

        <td><%= link_to 'Show', region_market_path(@region, market) %></td>
        <td><%= link_to 'Edit', edit_region_market_path(@region, market) %></td>
        <td><%= link_to 'Destroy', region_market_path(@region, market), method: :delete, data: { confirm: 'Are you sure?' } %></td>       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Market', new_region_market_path(@region) %>
</div>

<script type="text/javascript">
myresult= getResults('90210');
console.log(myresult);
searchResultsHandler(myresult);

function getResults(zip) {
    // or
    // function getResults(lat, lng) {
    $.ajax({
        type: "GET",
        contentType: "application/json; charset=utf-8",
        // submit a get request to the restful service zipSearch or locSearch.
        url: "http://search.ams.usda.gov/farmersmarkets/v1/data.svc/zipSearch?zip=" + zip,
        // or
        // url: "http://search.ams.usda.gov/farmersmarkets/v1/data.svc/locSearch?lat=" + lat + "&lng=" + lng,
        dataType: 'jsonp',
        jsonpCallback: 'searchResultsHandler'
    });
}

function searchResultsHandler(searchresults) {
    for (var key in searchresults) {
        // alert(key);
        var results = searchresults[key];
        for (var i = 0; i < results.length; i++) {
            var result = results[i];
            for (var key in result) {
                //only do an alert on the first search result
                if (i == 0) {
                    console.log(result[key]);
                }
            }
        }
    }
}
</script>

app/views/markets/local_listing.html.erb
<h3>Local Markets</h3>
<%= render 'layouts/markets' %>      

app/views/markets/new.html.erb
<div class="container">
	<h1>New Market</h1>

<%= render 'form' %>

<%= link_to 'Back', region_markets_path(@region) %>
</div>

app/views/markets/show.html.erb
<div class="container">
  <div class="row-fluid">      
    <div class="span6">
      <h2><%= @market.name %></h2
        <img src="<%= @market.image_url %>" >
        <p><%= @market.description %></p>
        <p>
    
        </p>
        <a href="http://maps.google.com/maps?saddr=<%= @market.address %>" target="mrk_directions"><p><%= @market.address %></p>
        <img src="http://maps.googleapis.com/maps/api/staticmap?center=<%= URI.escape(@market.address) %>&zoom=13&size=800x500&maptype=roadmap
        &markers=color:green%7Clabel:%7C<%= URI.escape(@market.address) %>&sensor=false"></a>       
    </div>
    <div class="span6">
     <h3>Market Times</h3>
      <table class="table">
      <% @times.each do |time| %>
      <tr>
        <td><%= time.day %></td>
        <td><%= time.start_time %></td>
        <td><%= time.end_time %></td>   
      </tr>
      <% end %>
     
    </table>
    </div>
  </div>
</div>
 