config/routes.rb
PeakSeason::Application.routes.draw do

  resources :regions do 
  end

  
  resources :items

  get "/local_recipes" => "recipes#local_listing"
  get "/markets/:id/:name" => "markets#detail"  
  get "/in_season" => "items#in_season_listing"
  get "/local_markets" => "markets#local_markets"

  get "/getmarkets" => 'markets#getmarkets'

  root :to  => "site#home"

 

  

  

end

app/models/region.rb
class Region
  include Mongoid::Document
  field :name, type: String
  field :country, type: String

  has_many :markets
  has_many :items

end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render action: 'show', status: :created, location: @region }
      else
        format.html { render action: 'new' }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:name, :country)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.erb
<%= form_for(@region) do |f| %>
  <% if @region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
      <% @region.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regions/edit.html.erb
<div class="container">
<h1>Editing region</h1>

<%= render 'form' %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>
</div>

app/views/regions/index.html.erb
<div class="container">
<h1>Regions Listing</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.name %></td>
        <td><%= region.country %></td>
        <td><%= link_to 'Show', region %></td>
        <td><%= link_to 'Edit', edit_region_path(region) %></td>
        <td><%= link_to 'Destroy', region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'View Markets', region_markets_path(@region) %>
          <%= link_to ':V2', "/regions/#{region.id}/markets" %></td>
        
        <td><%= link_to 'View Items', items_path(@region) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Region', new_region_path %>
</div>

app/views/regions/new.html.erb
<div class="container">
<h1>New region</h1>

<%= render 'form' %>

<%= link_to 'Back', regions_path %>
</div>

app/views/regions/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @region.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @region.country %>
</p>

<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regions_path %>
</div>